[toolchain]
channel = "stable"
components = [
  "rustc",
  "cargo",
  "rustfmt",
  "rust-std",
  "rust-docs",
  "rust-analyzer",
  "clippy",
  "rust-src",
  "llvm-tools",
]
targets = [
  # "x86_64-unknown-linux-gnu",
  # "x86_64-unknown-linux-musl",
  # "aarch64-unknown-linux-gnu",
  # "aarch64-unknown-linux-musl",
]
