unstable_features = true

edition = "2021"
condense_wildcard_suffixes = true
# blank_lines_upper_bound = 2
fn_single_line = true
format_code_in_doc_comments = true
format_strings = true
match_block_trailing_comma = true
imports_granularity = "Crate"
newline_style = "Unix"
normalize_doc_attributes = true
reorder_impl_items = true
reorder_imports = true
group_imports = "StdExternalCrate"
reorder_modules = true
report_fixme = "Always"
report_todo = "Always"
use_field_init_shorthand = true
wrap_comments = true
