[toolchain]
channel = "beta"
components = [
  "rustc",
  "rust-std",
  "cargo",
  "rust-docs",
  "rustfmt",
  "clippy",
  "rust-src",
  "llvm-tools-preview",
]
targets = [
  "x86_64-unknown-linux-gnu",
  # "x86_64-unknown-linux-musl",
  # "aarch64-unknown-linux-gnu",
  # "aarch64-unknown-linux-musl",
]
